"""编辑命令组"""
from commands.common import add_common_args


def register(subparsers):
    p = subparsers.add_parser('replace-text', help='替换整段文字')
    p.add_argument('file', help='输入 .docx 文件')
    p.add_argument('--paragraph', type=int, help='段落索引')
    p.add_argument('--by-text', help='包含此文本的段落（内容定位，优先于 --paragraph）')
    p.add_argument('--text', help='新文字')
    p.add_argument('--text-file', help='从文件读取替换文本')
    add_common_args(p)

    p = subparsers.add_parser('replace-inline', help='段内子串替换（保留原有格式，可指定新格式参数）')
    p.add_argument('file', help='输入 .docx 文件')
    p.add_argument('--paragraph', type=int, help='段落索引')
    p.add_argument('--by-text', help='包含此文本的段落（内容定位，优先于 --paragraph）')
    p.add_argument('--old', required=True, help='被替换的子串')
    p.add_argument('--new', default='', help='替换后的新子串（传空串=删除，如 --new ""）')
    p.add_argument('--delete', action='store_true', help='删除 --old 子串（PowerShell 友好，替代 --new ""）')
    p.add_argument('--bold', type=lambda s: s.lower() in ('true','1','yes'), nargs='?',
                   const=True, help='加粗')
    p.add_argument('--font', help='西文字体名')
    p.add_argument('--font-east', dest='font_east', help='东亚字体名')
    p.add_argument('--size', type=float, help='字号 (pt)')
    p.add_argument('--color', help='颜色十六进制 (如 FF0000)')
    add_common_args(p)

    p = subparsers.add_parser('format-inline', help='不改文字，仅修改段内子串格式（加粗/字体/字号/颜色）')
    p.add_argument('file', help='输入 .docx 文件')
    p.add_argument('--paragraph', type=int, help='段落索引')
    p.add_argument('--by-text', help='包含此文本的段落（内容定位，优先于 --paragraph）')
    p.add_argument('--target', required=True, help='要修改格式的目标子串')
    p.add_argument('--bold', type=lambda s: s.lower() in ('true','1','yes'), nargs='?',
                   const=True, help='加粗')
    p.add_argument('--font', help='西文字体名')
    p.add_argument('--font-east', dest='font_east', help='东亚字体名')
    p.add_argument('--size', type=float, help='字号 (pt)')
    p.add_argument('--color', help='颜色十六进制 (如 FF0000)')
    add_common_args(p)

    p = subparsers.add_parser('replace-batch', help='批量替换')
    p.add_argument('file', help='输入 .docx 文件')
    p.add_argument('--pairs', required=True, help='JSON格式替换对列表')
    p.add_argument('--chapter', type=int, help='限定章节')
    add_common_args(p)

    p = subparsers.add_parser('replace-batch-by-index', help='按段落索引批量替换')
    p.add_argument('file', help='输入 .docx 文件')
    p.add_argument('--pairs-file', required=True, help='JSON文件，格式: {"43": "新文本"}')
    add_common_args(p)

    p = subparsers.add_parser('insert-paragraph', help='插入段落')
    p.add_argument('file', help='输入 .docx 文件')
    p.add_argument('--after', type=int, required=True, help='在哪个段落之后插入（索引）')
    p.add_argument('--text', help='段落文字')
    p.add_argument('--text-file', help='从文件读取段落文字')
    p.add_argument('--style', default='body', help='Word 样式 (body|h1|h2|h3|caption|reference)')
    p.add_argument('--rules', help='自定义样式规则文件 (YAML)')
    add_common_args(p)

    p = subparsers.add_parser('write-paragraphs', help='批量插入多段（从后往前，防索引漂移）')
    p.add_argument('file', help='输入 .docx 文件')
    p.add_argument('--after', type=int, required=True, help='在哪个段落之后插入（索引）')
    p.add_argument('--data', help='JSON 数组（与 --data-file 二选一）')
    p.add_argument('--data-file', help='从文件读取段落数组 (JSON)')
    add_common_args(p)

    p = subparsers.add_parser('delete-paragraph', help='删除段落')
    p.add_argument('file', help='输入 .docx 文件')
    p.add_argument('--paragraph', type=int, help='段落索引')
    p.add_argument('--by-text', help='包含此文本的段落（内容定位，优先于 --paragraph）')
    add_common_args(p)

    p = subparsers.add_parser('set-format', help='设置段落格式')
    p.add_argument('file', help='输入 .docx 文件')
    p.add_argument('--paragraph', type=int, help='段落索引（单段落模式）')
    p.add_argument('--by-text', help='包含此文本的段落（内容定位，优先于 --paragraph）')
    p.add_argument('--start', type=int, help='起始段落索引（范围模式）')
    p.add_argument('--end', type=int, help='结束段落索引（范围模式）')
    p.add_argument('--target', choices=['body', 'headings'], help='批量目标')
    p.add_argument('--style', required=True, help='Word 样式名')
    p.add_argument('--rules', help='自定义样式规则文件 (YAML)')
    add_common_args(p)

    p = subparsers.add_parser('replace-table', help='替换表格内容')
    p.add_argument('file', help='输入 .docx 文件')
    p.add_argument('--index', type=int, required=True, help='表格索引')
    p.add_argument('--data', help='JSON二维数组（与 --data-file 二选一）')
    p.add_argument('--data-file', help='从文件读取表格数据 (JSON)')
    add_common_args(p)

    p = subparsers.add_parser('insert-table', help='在段落后插入表格')
    p.add_argument('file', help='输入 .docx 文件')
    p.add_argument('--after', type=int, required=True, help='在哪个段落之后插入（索引）')
    p.add_argument('--data', help='JSON二维数组（与 --data-file 二选一）')
    p.add_argument('--data-file', help='从文件读取表格数据 (JSON)')
    add_common_args(p)

    p = subparsers.add_parser('insert-image', help='在段落后插入图片')
    p.add_argument('file', help='输入 .docx 文件')
    p.add_argument('--after', type=int, required=True, help='在哪个段落之后插入（索引）')
    p.add_argument('--image', required=True, help='图片文件路径')
    p.add_argument('--width', type=float, help='图片宽度 (cm)')
    p.add_argument('--caption', help='图片标题')
    add_common_args(p)

    p = subparsers.add_parser('replace-image', help='替换文档中已有的图片')
    p.add_argument('file', help='输入 .docx 文件')
    p.add_argument('--image', required=True, help='新图片文件路径')
    p.add_argument('--caption', help='按图号标题定位')
    p.add_argument('--paragraph', type=int, help='按段落索引定位')
    p.add_argument('--media', help='按媒体文件名定位')
    add_common_args(p)

    p = subparsers.add_parser('delete-comments', help='删除所有批注')
    p.add_argument('file', help='输入 .docx 文件')
    add_common_args(p)

    # 搜索（属于读类但放在编辑组方便）
    p = subparsers.add_parser('search', help='关键词/正则/写作风格搜索')
    p.add_argument('file', help='输入 .docx 文件')
    p.add_argument('--query', default=None, help='搜索关键词或正则')
    p.add_argument('--from-file', dest='query_file', help='从文件读取搜索内容')
    p.add_argument('--regex', action='store_true', help='使用正则')
    p.add_argument('--writing-style', action='store_true', help='搜索常见写作风格问题（套路化开头/连接词堆砌/机械列举/预告句/冗余总结/摘要过长）')
    p.add_argument('--chapter', type=int, help='限定第N章')
    p.add_argument('--section', help='限定章节（标题名模糊匹配）')
    p.add_argument('--context', type=int, default=0, help='上下文段落数')
    p.add_argument('--limit', type=int, default=20, help='最大返回条数')

    p = subparsers.add_parser('search-by-style', help='按样式搜索')
    p.add_argument('file', help='输入 .docx 文件')
    p.add_argument('--style', required=True, help='样式名称')

    p = subparsers.add_parser('search-format', help='格式一致性检查')
    p.add_argument('file', help='输入 .docx 文件')
    p.add_argument('--target', choices=['headings', 'body', 'all'], default='all', help='检查目标')

    p = subparsers.add_parser('detect-revisions', help='检测修订、彩色文字、高亮等异常标记')
    p.add_argument('file', help='输入 .docx 文件')
    add_common_args(p)
